image: node:8.9.1

before_script:
  - npm install

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

mocha:
  script:
    - npm test

heroku:
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/lenin.git
    - git push -f heroku master
  stage: deploy
  only:
    - master
